services:
  - type: web
    name: cityrent
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:server --workers=1 --threads=4 --timeout=180 --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
